import type { ThemeDefinition } from 'vuetify'

// Palette institutionnelle DGTCP — République du Mali
export const staticPrimaryColor = '#08A04B'
export const staticPrimaryDarkenColor = '#067A39'

export const dgtcpColors = {
  vert: '#08A04B',
  vertDark: '#067A39',
  or: '#E7C936',
  rouge: '#E53935',
  noir: '#000000',
  blanc: '#FFFFFF',
  grisClair: '#F5F7FA',
  grisMoyen: '#DDE3EA',
  grisFonce: '#374151',
} as const

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#FFFFFF',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': dgtcpColors.grisFonce,
      'on-secondary': '#FFFFFF',
      'secondary-darken-1': '#1F2937',
      'success': staticPrimaryColor,
      'on-success': '#FFFFFF',
      'success-darken-1': staticPrimaryDarkenColor,
      'info': dgtcpColors.grisFonce,
      'on-info': '#FFFFFF',
      'info-darken-1': '#1F2937',
      'warning': dgtcpColors.or,
      'on-warning': dgtcpColors.noir,
      'warning-darken-1': '#C9AD2E',
      'error': dgtcpColors.rouge,
      'on-error': '#FFFFFF',
      'error-darken-1': '#C62828',
      'background': dgtcpColors.grisClair,
      'on-background': dgtcpColors.noir,
      'surface': dgtcpColors.blanc,
      'on-surface': dgtcpColors.noir,
      'grey-50': dgtcpColors.grisClair,
      'grey-100': '#EEF1F6',
      'grey-200': dgtcpColors.grisMoyen,
      'grey-300': '#C5CDD6',
      'grey-400': '#9CA3AF',
      'grey-500': '#6B7280',
      'grey-600': dgtcpColors.grisFonce,
      'grey-700': '#1F2937',
      'grey-800': '#111827',
      'grey-900': dgtcpColors.noir,
      'grey-light': dgtcpColors.grisClair,
      'perfect-scrollbar-thumb': dgtcpColors.grisMoyen,
      'skin-bordered-background': dgtcpColors.blanc,
      'skin-bordered-surface': dgtcpColors.blanc,
      'expansion-panel-text-custom-bg': dgtcpColors.grisClair,
    },

    variables: {
      'code-color': staticPrimaryColor,
      'overlay-scrim-background': dgtcpColors.noir,
      'tooltip-background': dgtcpColors.grisFonce,
      'overlay-scrim-opacity': 0.4,
      'hover-opacity': 0.04,
      'focus-opacity': 0.08,
      'selected-opacity': 0.06,
      'activated-opacity': 0.08,
      'pressed-opacity': 0.1,
      'dragged-opacity': 0.08,
      'disabled-opacity': 0.38,
      'border-color': dgtcpColors.grisMoyen,
      'border-opacity': 1,
      'table-header-color': dgtcpColors.grisClair,
      'high-emphasis-opacity': 0.92,
      'medium-emphasis-opacity': 0.68,
      'switch-opacity': 0.15,
      'switch-disabled-track-opacity': 0.25,
      'switch-disabled-thumb-opacity': 0.35,
      'switch-checked-disabled-opacity': 0.25,
      'track-bg': dgtcpColors.grisMoyen,
      'shadow-key-umbra-color': dgtcpColors.noir,
      'shadow-xs-opacity': 0.04,
      'shadow-sm-opacity': 0.06,
      'shadow-md-opacity': 0.08,
      'shadow-lg-opacity': 0.1,
      'shadow-xl-opacity': 0.12,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': '#2ECC71',
      'on-primary': dgtcpColors.noir,
      'primary-darken-1': staticPrimaryColor,
      'secondary': '#9CA3AF',
      'on-secondary': dgtcpColors.noir,
      'secondary-darken-1': '#6B7280',
      'success': '#2ECC71',
      'on-success': dgtcpColors.noir,
      'success-darken-1': staticPrimaryColor,
      'info': '#9CA3AF',
      'on-info': dgtcpColors.noir,
      'info-darken-1': '#6B7280',
      'warning': dgtcpColors.or,
      'on-warning': dgtcpColors.noir,
      'warning-darken-1': '#C9AD2E',
      'error': '#EF5350',
      'on-error': dgtcpColors.noir,
      'error-darken-1': dgtcpColors.rouge,
      'background': '#111827',
      'on-background': '#F3F4F6',
      'surface': '#1F2937',
      'on-surface': '#F3F4F6',
      'grey-50': '#1F2937',
      'grey-100': '#374151',
      'grey-200': '#4B5563',
      'grey-300': '#6B7280',
      'grey-400': '#9CA3AF',
      'grey-500': dgtcpColors.grisMoyen,
      'grey-600': '#E5E7EB',
      'grey-700': '#F3F4F6',
      'grey-800': dgtcpColors.grisClair,
      'grey-900': dgtcpColors.blanc,
      'grey-light': '#374151',
      'perfect-scrollbar-thumb': '#4B5563',
      'skin-bordered-background': '#1F2937',
      'skin-bordered-surface': '#1F2937',
    },
    variables: {
      'code-color': '#2ECC71',
      'overlay-scrim-background': dgtcpColors.noir,
      'tooltip-background': '#F3F4F6',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.1,
      'pressed-opacity': 0.12,
      'dragged-opacity': 0.08,
      'disabled-opacity': 0.4,
      'border-color': '#4B5563',
      'border-opacity': 0.5,
      'table-header-color': '#374151',
      'high-emphasis-opacity': 0.92,
      'medium-emphasis-opacity': 0.68,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#4B5563',
      'shadow-key-umbra-color': '#000000',
      'shadow-xs-opacity': 0.1,
      'shadow-sm-opacity': 0.12,
      'shadow-md-opacity': 0.14,
      'shadow-lg-opacity': 0.16,
      'shadow-xl-opacity': 0.18,
    },
  },
}

export default themes
